### PR TITLE
Change crawler behavior and crate initial dataset for the shopping malls

### PR DESCRIPTION
**Pull request by alonge**

### CODE REVIEW

**Comment by alonge** [comment]
Any ideas for the structure of the shopping mall json? @csvital

**Comment by csvital** [comment]
> Any ideas for the structure of the shopping mall json? @csvital

Looks good enough

**Comment by alonge** [comment]
DO NOT MERGE, change incoming

**Comment by alonge** [comment]
Latest version of the shopping mall data json structure:

```json
{
	"ImageLink": "",
	"DetailPage": "",
	"Name": "",
	"Score": "",
	"District": "",
	"City": "",
	"Shops": [{
		"Logo": "",
		"Magaza": "",
		"Kat": "",
		"Telefon": ""
	}],
	"Cafes": [{
		"Logo": "",
		"Magaza": "",
		"Kat": "",
		"Telefon": ""
	}]
}

Also the data.txt file can be consumed using consumer package directly to mongo

**Comment by alonge** [comment]
@csvital Ready for review!

**Comment by csvital** [comment]
We might change field names from Turkish to English? Yeah I know I did it first :(

**Pull request merged**
